// From Colour.h in OpenRCT2.

export enum Colour {
  Black,
  Grey,
  White,
  DarkPurple,
  LightPurple,
  BrightPurple,
  DarkBlue,
  LightBlue,
  IcyBlue,
  Teal,
  Aquamarine,
  SaturatedGreen,
  DarkGreen,
  MossGreen,
  BrightGreen,
  OliveGreen,
  DarkOliveGreen,
  BrightYellow,
  Yellow,
  DarkYellow,
  LightOrange,
  DarkOrange,
  LightBrown,
  SaturatedBrown,
  DarkBrown,
  SalmonPink,
  BordeauxRed,
  SaturatedRed,
  BrightRed,
  DarkPink,
  BrightPink,
  LightPink
}
